"""
COVID-19 Mortality Prediction — Streamlit Dashboard
Tabs: Executive Summary | EDA | Model Performance | Feature Selection | SHAP Analysis
Pre-trained models must be generated by running train_models.py first.
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import joblib
import os
import json
import io
import warnings

from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import cross_validate, KFold
from sklearn.metrics import roc_auc_score

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

warnings.filterwarnings("ignore")

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
DATA_PATH  = os.path.join(BASE_DIR, "covid.csv")
OUT_DIR    = os.path.join(BASE_DIR, "pipeline_outputs")
MODELS_DIR = os.path.join(OUT_DIR, "models")
PLOTS_DIR  = os.path.join(OUT_DIR, "plots")
SHAP_DIR   = os.path.join(OUT_DIR, "shap")

TARGET   = "DEATH"
ALL_FEATURES = [
    "SEX","HOSPITALIZED","PNEUMONIA","AGE","PREGNANT","DIABETES",
    "COPD","ASTHMA","IMMUNOSUPPRESSION","HYPERTENSION","OTHER_DISEASE",
    "CARDIOVASCULAR","OBESITY","RENAL_CHRONIC","TOBACCO","COVID_POSITIVE",
]

MODEL_COLORS = {
    "Linear Regression": "#3498DB",
    "Lasso":             "#2ECC71",
    "Ridge":             "#9B59B6",
    "CART":              "#E74C3C",
    "Random Forest":     "#F39C12",
    "LightGBM":          "#1ABC9C",
}

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="COVID-19 Mortality ML Dashboard",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
.main-header {
    font-size:2.2rem; font-weight:800; color:#1a237e;
    text-align:center; padding:10px 0;
    border-bottom:3px solid #3f51b5; margin-bottom:18px;
}
.sub-header { font-size:1.35rem; color:#283593; font-weight:700; margin-bottom:10px; }
.kpi-card {
    background:linear-gradient(135deg,#e8eaf6,#c5cae9);
    border-radius:12px; padding:16px; text-align:center;
    border-left:5px solid #3f51b5; margin-bottom:8px;
}
.kpi-value { font-size:2rem; font-weight:800; color:#1a237e; }
.kpi-label { font-size:0.88rem; color:#455a64; margin-top:4px; }
.insight-box {
    background:#e3f2fd; border-radius:8px; padding:13px;
    border-left:5px solid #1565c0; margin:8px 0;
}
.warning-box {
    background:#fff3e0; border-radius:8px; padding:13px;
    border-left:5px solid #ef6c00; margin:8px 0;
}
.success-box {
    background:#e8f5e9; border-radius:8px; padding:13px;
    border-left:5px solid #2e7d32; margin:8px 0;
}
.section-divider { border-top:2px solid #e0e0e0; margin:20px 0; }
</style>
""", unsafe_allow_html=True)

# ── Cached loaders ─────────────────────────────────────────────────────────────
@st.cache_data(show_spinner=False)
def load_data():
    return pd.read_csv(DATA_PATH)

@st.cache_resource(show_spinner=False)
def load_models():
    models = {}
    for name in MODEL_COLORS:
        path = os.path.join(MODELS_DIR, f"{name.replace(' ','_')}.pkl")
        if os.path.exists(path):
            models[name] = joblib.load(path)
    return models

@st.cache_data(show_spinner=False)
def load_cv_results():
    p = os.path.join(OUT_DIR, "cv_results.csv")
    return pd.read_csv(p, index_col=0) if os.path.exists(p) else None

@st.cache_resource(show_spinner=False)
def load_shap_data():
    p = os.path.join(SHAP_DIR, "shap_values.pkl")
    return joblib.load(p) if os.path.exists(p) else {}

@st.cache_data(show_spinner=False)
def load_stats():
    p = os.path.join(OUT_DIR, "dataset_stats.json")
    return json.load(open(p)) if os.path.exists(p) else {}

def show_img(path, caption=None):
    if os.path.exists(path):
        st.image(path, use_container_width=True, caption=caption)
    else:
        st.warning(f"Image not found: {os.path.basename(path)}")

def mpl_to_bytes(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=150)
    buf.seek(0)
    return buf

# ── Sidebar ────────────────────────────────────────────────────────────────────
stats = load_stats()
with st.sidebar:
    st.markdown("## 🏥 COVID-19 Mortality\n### ML Dashboard")
    st.markdown("---")
    if stats:
        st.metric("Total Patients",  f"{stats.get('total_rows', 0):,}")
        st.metric("Features",         stats.get("n_features", 16))
        st.metric("Mortality Rate",   f"{stats.get('death_rate', 0)*100:.1f}%")
        st.metric("Training Sample",  f"{stats.get('sample_rows', 200000):,}")
    st.markdown("---")
    st.markdown("**Models:** Linear, Lasso, Ridge,\nCART, Random Forest, LightGBM")
    st.markdown("**CV:** 5-Fold Cross-Validation")
    st.markdown("**Target:** DEATH (binary)")
    st.markdown("---")
    st.caption("Note: Dataset is about COVID-19 mortality, not hurricane forecasting.")

# ── Header ─────────────────────────────────────────────────────────────────────
st.markdown(
    '<div class="main-header">🏥 COVID-19 Mortality Prediction — ML Dashboard</div>',
    unsafe_allow_html=True,
)

# ── Tabs ───────────────────────────────────────────────────────────────────────
tabs = st.tabs([
    "📋 Executive Summary",
    "📊 Data Overview & EDA",
    "🤖 Model Performance",
    "🎛️ Feature Selection",
    "🔍 SHAP Analysis",
])

# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — EXECUTIVE SUMMARY
# ══════════════════════════════════════════════════════════════════════════════
with tabs[0]:
    st.markdown('<div class="sub-header">Executive Summary</div>', unsafe_allow_html=True)
    cv_df  = load_cv_results()

    # KPI row
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-value">{stats.get('total_rows', 1021978):,}</div>
            <div class="kpi-label">Patient Records</div></div>""", unsafe_allow_html=True)
    with c2:
        dr = stats.get("death_rate", 0.131)*100
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-value">{dr:.1f}%</div>
            <div class="kpi-label">Overall Mortality Rate</div></div>""", unsafe_allow_html=True)
    with c3:
        best_m = cv_df["AUC"].idxmax() if cv_df is not None else "LightGBM"
        best_auc = cv_df["AUC"].max() if cv_df is not None else 0.0
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-value">{best_auc:.3f}</div>
            <div class="kpi-label">Best AUC ({best_m})</div></div>""", unsafe_allow_html=True)
    with c4:
        best_r2 = cv_df["CV R2"].max() if cv_df is not None else 0.0
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-value">{best_r2:.3f}</div>
            <div class="kpi-label">Best R² (CV)</div></div>""", unsafe_allow_html=True)

    st.markdown('<div class="section-divider"></div>', unsafe_allow_html=True)
    col_l, col_r = st.columns([3, 2])

    with col_l:
        st.markdown("""
## 🎯 Project Overview

This dashboard presents a **complete machine learning pipeline** for predicting COVID-19 patient
mortality using Mexico's official COVID-19 patient registry — one of the largest publicly available
clinical datasets with over **1 million patient records**.

---

## 📊 Dataset at a Glance

| Attribute | Value |
|-----------|-------|
| Source | Mexico DGIS COVID-19 Open Data |
| Total Records | 1,021,977 patients |
| Training Sample | 200,000 (stratified random) |
| Features | 16 clinical & demographic |
| Target Variable | DEATH (0 = survived, 1 = died) |
| Baseline Mortality Rate | ~13.1% |
| Class Imbalance Ratio | ~1 : 6.6 |

---

## 🔬 Key Clinical Findings

""")
        insights = [
            ("📈", "Age is the single strongest predictor",
             "Patients aged 80+ face >30% mortality vs <2% for under-20s. "
             "Risk increases sharply after age 50."),
            ("🫁", "Pneumonia drives mortality far above any other comorbidity",
             "COVID patients with pneumonia: ~28% mortality vs ~6% without — a 4.6× increase."),
            ("🏥", "Hospitalization is a key risk marker",
             "Hospitalized patients with multiple comorbidities show dramatically elevated risk."),
            ("🫀", "Cardiovascular disease & chronic kidney disease compound risk",
             "Combined with age ≥60, these conditions are multiplicative risk amplifiers."),
            ("🧬", "COVID-positive status interacts non-linearly",
             "COVID+ patients without comorbidities have lower absolute mortality than COVID- "
             "elderly patients with multiple conditions — highlighting importance of holistic risk assessment."),
        ]
        for icon, title, body in insights:
            st.markdown(
                f'<div class="insight-box">{icon} <strong>{title}</strong><br>{body}</div>',
                unsafe_allow_html=True,
            )

        st.markdown("""
---

## 🤖 Model Performance Summary
""")
        if cv_df is not None:
            display = cv_df[["CV RMSE","CV R2","CV MAE","AUC","Train RMSE","Train R2"]].round(4)
            st.dataframe(
                display.style
                    .highlight_min(subset=["CV RMSE","CV MAE","Train RMSE"], color="#c8e6c9")
                    .highlight_max(subset=["CV R2","AUC","Train R2"], color="#c8e6c9"),
                use_container_width=True,
            )

        st.markdown("---\n## 🏆 Recommendation")
        if cv_df is not None:
            best = cv_df["AUC"].idxmax()
            st.markdown(f"""
<div class="success-box">
✅ <strong>Recommended model: {best}</strong><br>
Achieves AUC = {cv_df.loc[best,"AUC"]:.4f} and R² = {cv_df.loc[best,"CV R2"]:.4f}.
Ensemble tree methods capture the non-linear interactions between age,
comorbidities, and COVID severity that linear models cannot represent.
For production clinical deployment, this model should be combined with
calibration and fairness auditing.
</div>
""", unsafe_allow_html=True)

        st.markdown("---\n## ⚠️ Limitations & Ethics")
        warnings_list = [
            ("Class imbalance",
             "Only ~13% of patients died. SMOTE or class-weighted training may improve minority-class recall."),
            ("Regression for binary target",
             "Linear, Lasso, and Ridge predict continuous scores; AUC is computed by treating "
             "raw outputs as probability estimates."),
            ("External validity",
             "Trained exclusively on Mexican registry data. Performance may differ in other "
             "healthcare systems or demographic groups."),
            ("Not a clinical tool",
             "This model is for educational and research purposes only. "
             "It must not replace clinical judgment."),
            ("Feature granularity",
             "Binary encoding of comorbidities loses severity/duration nuance present in richer EHR data."),
        ]
        for title, body in warnings_list:
            st.markdown(
                f'<div class="warning-box">⚠️ <strong>{title}:</strong> {body}</div>',
                unsafe_allow_html=True,
            )

    with col_r:
        st.markdown("### 📊 Model Snapshot")
        if cv_df is not None:
            fig_auc = go.Figure(go.Bar(
                y=cv_df.index, x=cv_df["AUC"], orientation="h",
                marker_color=[MODEL_COLORS.get(n,"#888") for n in cv_df.index],
                text=[f"{v:.3f}" for v in cv_df["AUC"]], textposition="outside",
            ))
            fig_auc.add_vline(x=0.5, line_dash="dash", line_color="gray")
            fig_auc.update_layout(
                title="AUC by Model", height=300,
                xaxis_title="AUC", margin=dict(l=0,r=50,t=40,b=20),
                plot_bgcolor="#f8f9fa",
            )
            st.plotly_chart(fig_auc, use_container_width=True)

            fig_r2 = go.Figure(go.Bar(
                y=cv_df.index, x=cv_df["CV R2"], orientation="h",
                marker_color=[MODEL_COLORS.get(n,"#888") for n in cv_df.index],
                text=[f"{v:.3f}" for v in cv_df["CV R2"]], textposition="outside",
            ))
            fig_r2.update_layout(
                title="CV R² by Model", height=300,
                xaxis_title="R²", margin=dict(l=0,r=50,t=40,b=20),
                plot_bgcolor="#f8f9fa",
            )
            st.plotly_chart(fig_r2, use_container_width=True)

        st.markdown("### 🔍 SHAP Feature Importance (LightGBM)")
        shap_bar = os.path.join(SHAP_DIR, "shap_bar_LightGBM.png")
        show_img(shap_bar)

        st.markdown("### 📌 Quick Stats")
        if cv_df is not None:
            best_rmse = cv_df["CV RMSE"].idxmin()
            st.metric("Best RMSE", f"{cv_df['CV RMSE'].min():.4f}", delta=f"({best_rmse})")
            best_r2_m = cv_df["CV R2"].idxmax()
            st.metric("Best R²", f"{cv_df['CV R2'].max():.4f}", delta=f"({best_r2_m})")
            st.metric("Best AUC", f"{cv_df['AUC'].max():.4f}", delta=f"({cv_df['AUC'].idxmax()})")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — EDA
# ══════════════════════════════════════════════════════════════════════════════
with tabs[1]:
    st.markdown('<div class="sub-header">📊 Data Overview & Exploratory Analysis</div>',
                unsafe_allow_html=True)

    df = load_data()
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Rows",     f"{len(df):,}")
    c2.metric("Columns",        len(df.columns))
    c3.metric("Mortality Rate", f"{df[TARGET].mean()*100:.2f}%")
    c4.metric("Missing Values", f"{df.isnull().sum().sum():,}")

    with st.expander("📋 Dataset Preview (first 10 rows)"):
        st.dataframe(df.head(10), use_container_width=True)
    with st.expander("📈 Descriptive Statistics"):
        st.dataframe(df.describe().round(3), use_container_width=True)

    st.markdown("---")

    # Interactive age chart
    st.markdown("### 🎯 Interactive: Death Rate by 5-Year Age Band")
    df_tmp2 = df.copy()
    df_tmp2["age_group"] = pd.cut(df_tmp2["AGE"], bins=list(range(0,121,5)),
                                   labels=[f"{i}–{i+4}" for i in range(0,116,5)])
    ag2 = df_tmp2.groupby("age_group", observed=True)[TARGET].agg(["mean","count"]).reset_index()
    ag2.columns = ["Age Group","Death Rate","Patient Count"]
    ag2["Death Rate"] *= 100

    fig_int = make_subplots(specs=[[{"secondary_y": True}]])
    fig_int.add_trace(
        go.Bar(x=ag2["Age Group"], y=ag2["Death Rate"], name="Death Rate (%)",
               marker_color="crimson", opacity=0.72),
        secondary_y=False,
    )
    fig_int.add_trace(
        go.Scatter(x=ag2["Age Group"], y=ag2["Patient Count"], name="Patient Count",
                   line=dict(color="steelblue", width=2), mode="lines+markers"),
        secondary_y=True,
    )
    fig_int.update_layout(title="Death Rate & Patient Count by Age Band", height=420,
                          plot_bgcolor="#f8f9fa", xaxis=dict(tickangle=45))
    fig_int.update_yaxes(title_text="Death Rate (%)", secondary_y=False)
    fig_int.update_yaxes(title_text="Patient Count", secondary_y=True)
    st.plotly_chart(fig_int, use_container_width=True)

    st.markdown("---")

    # Static EDA plots
    sections = [
        ("Class Balance",          ["01_class_balance.png"],            1),
        ("Age Distribution",       ["02_age_distribution.png",
                                    "03_age_group_death.png"],          2),
        ("Feature Prevalence",     ["04_feature_prevalence.png"],       1),
        ("Death Rate by Condition",["05_death_rate_by_condition.png"],  1),
        ("Correlation Heatmap",    ["06_correlation_heatmap.png"],      1),
        ("Feature Impact Grid",    ["07_death_rate_grid.png"],          1),
        ("Sex Analysis",           ["08_sex_analysis.png"],             1),
        ("Age by Comorbidity",     ["09_age_by_condition.png"],         1),
        ("Comorbidity Co-occurrence",["10_comorbidity_cooccurrence.png"],1),
        ("Hospitalization & Sex",  ["11_hospitalized_sex_death.png"],   1),
        ("COVID Status vs Death",  ["12_covid_positive_death.png"],     1),
    ]
    for title, files, ncols in sections:
        st.markdown(f"### {title}")
        if ncols == 1:
            for f in files:
                show_img(os.path.join(PLOTS_DIR, f))
        else:
            cols = st.columns(ncols)
            for i, f in enumerate(files):
                with cols[i]:
                    show_img(os.path.join(PLOTS_DIR, f))
        st.markdown('<div class="section-divider"></div>', unsafe_allow_html=True)

    # Interactive feature heatmap
    st.markdown("### 🔥 Interactive Feature vs. Target Heatmap")
    binary_f = [c for c in ALL_FEATURES if c != "AGE"]
    dr_table = pd.DataFrame({
        "Feature": binary_f,
        "Death Rate (Has=1)": [df[df[c]==1][TARGET].mean()*100 for c in binary_f],
        "Death Rate (Not=0)": [df[df[c]==0][TARGET].mean()*100 for c in binary_f],
        "Prevalence (%)":     [df[c].mean()*100 for c in binary_f],
    }).sort_values("Death Rate (Has=1)", ascending=False)
    fig_heat2 = px.bar(
        dr_table, x="Feature", y=["Death Rate (Has=1)","Death Rate (Not=0)"],
        barmode="group", title="Death Rate: With vs. Without Each Condition",
        color_discrete_map={"Death Rate (Has=1)":"crimson","Death Rate (Not=0)":"steelblue"},
    )
    fig_heat2.update_layout(height=420, plot_bgcolor="#f8f9fa", xaxis=dict(tickangle=30))
    st.plotly_chart(fig_heat2, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — MODEL PERFORMANCE
# ══════════════════════════════════════════════════════════════════════════════
with tabs[2]:
    st.markdown('<div class="sub-header">🤖 Model Performance & Comparison</div>',
                unsafe_allow_html=True)
    cv_df = load_cv_results()

    if cv_df is None:
        st.error("⚠️  CV results not found. Run `train_models.py` first.")
        st.stop()

    st.info(
        "All models trained on a **200,000-patient sample** using **5-fold KFold CV**. "
        "RMSE and R² treat DEATH (0/1) as a continuous regression target. "
        "AUC-ROC is computed by treating regression scores as mortality probabilities."
    )

    # Full metric table
    st.markdown("#### 📋 Complete Cross-Validation Results")
    display = cv_df[["CV RMSE","CV RMSE Std","CV R2","CV R2 Std","CV MAE","CV MAE Std",
                      "AUC","Train RMSE","Train R2"]].round(4)
    st.dataframe(
        display.style
            .highlight_min(subset=["CV RMSE","CV MAE","Train RMSE"], color="#c8e6c9")
            .highlight_max(subset=["CV R2","AUC","Train R2"], color="#c8e6c9"),
        use_container_width=True,
    )

    st.markdown("---")
    st.markdown("#### 📊 Plotly Comparison Charts")
    fig_comp = make_subplots(
        rows=2, cols=2,
        subplot_titles=["CV RMSE (↓ better)","CV R² (↑ better)",
                         "AUC-ROC (↑ better)","Overfitting: Train vs CV RMSE"],
    )
    ml = list(cv_df.index)
    mc = [MODEL_COLORS.get(m,"#888") for m in ml]

    fig_comp.add_trace(go.Bar(y=ml, x=cv_df["CV RMSE"], orientation="h", marker_color=mc,
                               error_x=dict(array=cv_df["CV RMSE Std"].tolist(), visible=True),
                               name="CV RMSE"), row=1, col=1)
    fig_comp.add_trace(go.Bar(y=ml, x=cv_df["CV R2"], orientation="h", marker_color=mc,
                               error_x=dict(array=cv_df["CV R2 Std"].tolist(), visible=True),
                               name="CV R²"), row=1, col=2)
    fig_comp.add_trace(go.Bar(y=ml, x=cv_df["AUC"], orientation="h", marker_color=mc,
                               name="AUC"), row=2, col=1)
    fig_comp.add_trace(go.Bar(x=ml, y=cv_df["Train RMSE"], name="Train RMSE",
                               marker_color="steelblue", opacity=0.85), row=2, col=2)
    fig_comp.add_trace(go.Bar(x=ml, y=cv_df["CV RMSE"], name="CV RMSE",
                               marker_color="crimson", opacity=0.85), row=2, col=2)
    fig_comp.add_shape(type="line", x0=-0.5, x1=len(ml)-0.5, y0=0.5, y1=0.5,
                        line=dict(color="gray", dash="dash"), row=2, col=1)
    fig_comp.update_layout(height=680, barmode="group", plot_bgcolor="#f8f9fa", showlegend=False,
                            title_text="Model Comparison Dashboard", title_font_size=15)
    st.plotly_chart(fig_comp, use_container_width=True)

    # Static high-res comparison
    st.markdown("#### 📉 High-Resolution Comparison (Static)")
    show_img(os.path.join(PLOTS_DIR, "13_model_comparison.png"))

    st.markdown("---")
    st.markdown("#### 🕸️ Radar Chart — Multi-Metric Model Profile")

    radar_df = cv_df[["AUC","CV R2","CV RMSE","CV MAE"]].copy()
    radar_df["norm_AUC"]  = (radar_df["AUC"]    - radar_df["AUC"].min())    / (radar_df["AUC"].max()    - radar_df["AUC"].min()    + 1e-9)
    radar_df["norm_R2"]   = (radar_df["CV R2"]  - radar_df["CV R2"].min())  / (radar_df["CV R2"].max()  - radar_df["CV R2"].min()  + 1e-9)
    radar_df["norm_RMSE"] = 1 - (radar_df["CV RMSE"] - radar_df["CV RMSE"].min()) / (radar_df["CV RMSE"].max() - radar_df["CV RMSE"].min() + 1e-9)
    radar_df["norm_MAE"]  = 1 - (radar_df["CV MAE"]  - radar_df["CV MAE"].min())  / (radar_df["CV MAE"].max()  - radar_df["CV MAE"].min()  + 1e-9)
    cats = ["AUC","R²","1-RMSE","1-MAE"]

    fig_radar = go.Figure()
    for model_r in radar_df.index:
        vals = [radar_df.loc[model_r,"norm_AUC"], radar_df.loc[model_r,"norm_R2"],
                radar_df.loc[model_r,"norm_RMSE"], radar_df.loc[model_r,"norm_MAE"]]
        fig_radar.add_trace(go.Scatterpolar(
            r=vals+[vals[0]], theta=cats+[cats[0]],
            fill="toself", name=model_r, opacity=0.55,
            line=dict(color=MODEL_COLORS.get(model_r,"#888"), width=2),
        ))
    fig_radar.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0,1])),
        title="Normalized Model Performance Radar (1 = best)", height=480,
        legend=dict(orientation="h", yanchor="bottom", y=-0.15, xanchor="center", x=0.5),
    )
    st.plotly_chart(fig_radar, use_container_width=True)

    st.markdown("---")
    st.markdown("#### 📦 Box-plot of CV Fold Scores (recomputed on display)")
    st.caption("For deeper fold-level analysis, re-run `train_models.py` with `return_estimator=True`.")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 — FEATURE SELECTION
# ══════════════════════════════════════════════════════════════════════════════
with tabs[3]:
    st.markdown('<div class="sub-header">🎛️ Feature Selection — Performance Evolution</div>',
                unsafe_allow_html=True)
    st.markdown("""
Select features, choose a sample size and CV folds, then click **Run Models** to retrain
all six models with your chosen feature set. Results are compared against the full-feature baseline.
""")

    col_left, col_right = st.columns([1, 2])

    with col_left:
        st.markdown("### ✅ Select Features")

        st.markdown("**Demographics**")
        f_sex  = st.checkbox("SEX",                   value=True,  key="f_sex")
        f_age  = st.checkbox("AGE",                   value=True,  key="f_age")
        f_preg = st.checkbox("PREGNANT",              value=False, key="f_preg")

        st.markdown("**Clinical Status**")
        f_hosp = st.checkbox("HOSPITALIZED",          value=True,  key="f_hosp")
        f_pneu = st.checkbox("PNEUMONIA",             value=True,  key="f_pneu")
        f_cov  = st.checkbox("COVID_POSITIVE",        value=True,  key="f_cov")

        st.markdown("**Comorbidities**")
        f_diab = st.checkbox("DIABETES",              value=True,  key="f_diab")
        f_copd = st.checkbox("COPD",                  value=True,  key="f_copd")
        f_asth = st.checkbox("ASTHMA",                value=False, key="f_asth")
        f_immu = st.checkbox("IMMUNOSUPPRESSION",     value=False, key="f_immu")
        f_hyp  = st.checkbox("HYPERTENSION",          value=True,  key="f_hyp")
        f_oth  = st.checkbox("OTHER_DISEASE",         value=False, key="f_oth")
        f_card = st.checkbox("CARDIOVASCULAR",        value=True,  key="f_card")
        f_obes = st.checkbox("OBESITY",               value=True,  key="f_obes")
        f_ren  = st.checkbox("RENAL_CHRONIC",         value=True,  key="f_ren")
        f_tob  = st.checkbox("TOBACCO",               value=False, key="f_tob")

        feat_map = {
            "SEX": f_sex, "AGE": f_age, "PREGNANT": f_preg,
            "HOSPITALIZED": f_hosp, "PNEUMONIA": f_pneu, "COVID_POSITIVE": f_cov,
            "DIABETES": f_diab, "COPD": f_copd, "ASTHMA": f_asth,
            "IMMUNOSUPPRESSION": f_immu, "HYPERTENSION": f_hyp, "OTHER_DISEASE": f_oth,
            "CARDIOVASCULAR": f_card, "OBESITY": f_obes, "RENAL_CHRONIC": f_ren,
            "TOBACCO": f_tob,
        }
        sel_feats = [k for k, v in feat_map.items() if v]

        st.markdown("---")
        st.markdown(f"**Selected: {len(sel_feats)} / {len(ALL_FEATURES)} features**")
        if sel_feats:
            st.caption(", ".join(sel_feats))

        st.markdown("---")
        cv_folds_pick   = st.selectbox("CV Folds",            [3, 5, 10], index=1, key="cv_folds")
        sample_pick     = st.selectbox("Training Sample Size", [10_000, 25_000, 50_000], index=1,
                                        key="sample_pick")
        run_btn = st.button("🚀 Run Models", type="primary", use_container_width=True)

    with col_right:
        if not run_btn:
            st.info("👈 Select features on the left, then click **Run Models**.")
            cv_base = load_cv_results()
            if cv_base is not None:
                st.markdown("### Baseline — All 16 Features, 200K Sample")
                st.dataframe(cv_base[["CV RMSE","CV R2","AUC"]].round(4), use_container_width=True)
        else:
            if len(sel_feats) < 1:
                st.error("Please select at least one feature.")
            else:
                with st.spinner(f"Training 6 models on {sample_pick:,} rows with "
                                f"{len(sel_feats)} features…"):
                    df_live = load_data().sample(n=sample_pick, random_state=42)
                    X_live  = df_live[sel_feats]
                    y_live  = df_live[TARGET]

                    live_models = {
                        "Linear Regression": LinearRegression(),
                        "Lasso":             Lasso(alpha=0.0005, max_iter=3000),
                        "Ridge":             Ridge(alpha=1.0),
                        "CART":              DecisionTreeRegressor(max_depth=8, random_state=42),
                        "Random Forest":     RandomForestRegressor(
                            n_estimators=50, max_depth=10, n_jobs=-1, random_state=42),
                        "LightGBM":          LGBMRegressor(
                            n_estimators=100, learning_rate=0.05, n_jobs=-1,
                            random_state=42, verbose=-1),
                    }
                    kf    = KFold(n_splits=cv_folds_pick, shuffle=True, random_state=42)
                    live_res = {}
                    prog = st.progress(0)

                    for i, (mname, mobj) in enumerate(live_models.items()):
                        sc = cross_validate(
                            mobj, X_live, y_live, cv=kf,
                            scoring={"neg_rmse":"neg_root_mean_squared_error",
                                     "r2":"r2", "neg_mae":"neg_mean_absolute_error"},
                            n_jobs=1,
                        )
                        mobj.fit(X_live, y_live)
                        preds = np.clip(mobj.predict(X_live), 0, 1)
                        auc   = roc_auc_score(y_live, preds)
                        live_res[mname] = {
                            "CV RMSE": -sc["test_neg_rmse"].mean(),
                            "CV R2":    sc["test_r2"].mean(),
                            "CV MAE":  -sc["test_neg_mae"].mean(),
                            "AUC":      auc,
                        }
                        prog.progress((i+1) / len(live_models))

                live_df = pd.DataFrame(live_res).T.round(4)

                st.success(f"✅ Done! Trained with **{len(sel_feats)} features** on "
                           f"**{sample_pick:,} patients**.")

                st.markdown("### Results with Selected Features")
                st.dataframe(
                    live_df.style
                        .highlight_min(subset=["CV RMSE","CV MAE"], color="#c8e6c9")
                        .highlight_max(subset=["CV R2","AUC"], color="#c8e6c9"),
                    use_container_width=True,
                )

                # Comparison
                cv_base = load_cv_results()
                if cv_base is not None:
                    st.markdown("### 📊 Selected Features vs. Full Baseline")
                    shared = [m for m in live_df.index if m in cv_base.index]

                    fig_cmp = make_subplots(1, 2, subplot_titles=["AUC","RMSE"])
                    fig_cmp.add_trace(go.Bar(
                        name="Selected", x=shared,
                        y=[live_df.loc[m,"AUC"] for m in shared],
                        marker_color="steelblue", opacity=0.85,
                    ), row=1, col=1)
                    fig_cmp.add_trace(go.Bar(
                        name="Baseline (all feats)", x=shared,
                        y=[cv_base.loc[m,"AUC"] for m in shared if m in cv_base.index],
                        marker_color="lightgray", opacity=0.85,
                    ), row=1, col=1)
                    fig_cmp.add_trace(go.Bar(
                        name="Selected", x=shared,
                        y=[live_df.loc[m,"CV RMSE"] for m in shared],
                        marker_color="crimson", opacity=0.85,
                    ), row=1, col=2)
                    fig_cmp.add_trace(go.Bar(
                        name="Baseline (all feats)", x=shared,
                        y=[cv_base.loc[m,"CV RMSE"] for m in shared if m in cv_base.index],
                        marker_color="lightgray", opacity=0.85,
                    ), row=1, col=2)
                    fig_cmp.update_layout(height=380, barmode="group",
                                          plot_bgcolor="#f8f9fa", showlegend=True)
                    st.plotly_chart(fig_cmp, use_container_width=True)

                    # Delta table
                    delta_rows = {}
                    for m in shared:
                        b_auc = cv_base.loc[m,"AUC"];   l_auc = live_df.loc[m,"AUC"]
                        b_r2  = cv_base.loc[m,"CV R2"]; l_r2  = live_df.loc[m,"CV R2"]
                        b_rmse= cv_base.loc[m,"CV RMSE"];l_rmse=live_df.loc[m,"CV RMSE"]
                        delta_rows[m] = {
                            "ΔAUC":  round(l_auc - b_auc, 4),
                            "ΔR²":   round(l_r2  - b_r2,  4),
                            "ΔRMSE": round(l_rmse - b_rmse,4),
                        }
                    delta_df = pd.DataFrame(delta_rows).T
                    st.markdown("#### Δ Delta vs. Baseline (+ = selected better, − = baseline better)")
                    st.dataframe(
                        delta_df.style
                            .applymap(lambda v: "color:green" if v > 0 else "color:red", subset=["ΔAUC","ΔR²"])
                            .applymap(lambda v: "color:green" if v < 0 else "color:red", subset=["ΔRMSE"]),
                        use_container_width=True,
                    )

                # Quick SHAP on selected features
                st.markdown("### 🔍 Quick SHAP (LightGBM — Selected Features)")
                try:
                    lgbm_live = live_models["LightGBM"]
                    bg = X_live.sample(n=min(300, len(X_live)), random_state=42)
                    exp = shap.TreeExplainer(lgbm_live, bg)
                    sv  = exp.shap_values(bg)
                    fig_sq, _ = plt.subplots(figsize=(10, 5))
                    shap.summary_plot(sv, bg, show=False, plot_type="bar")
                    plt.title("SHAP Feature Importance (LightGBM — Selected Features)",
                              fontweight="bold")
                    plt.tight_layout()
                    st.pyplot(fig_sq)
                    plt.close("all")
                except Exception as e:
                    st.warning(f"Quick SHAP unavailable: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 5 — SHAP ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════
with tabs[4]:
    st.markdown('<div class="sub-header">🔍 SHAP Analysis — Model Explainability</div>',
                unsafe_allow_html=True)
    st.markdown("""
**SHAP** (SHapley Additive exPlanations) assigns each feature a contribution value for every prediction.
They are grounded in cooperative game theory and satisfy *efficiency*, *symmetry*, *dummy*, and *additivity* axioms,
making them the gold standard for ML interpretability.
""")

    shap_data = load_shap_data()
    if not shap_data:
        st.error("⚠️  SHAP data not found. Run `train_models.py` first.")
        st.stop()

    col_sel, col_info = st.columns([1, 3])
    with col_sel:
        sel_model_shap = st.selectbox("Select Model", list(shap_data.keys()),
                                       index=len(shap_data)-1, key="shap_model")
    with col_info:
        ev = shap_data[sel_model_shap].get("expected_value", 0.0) or 0.0
        st.info(f"**{sel_model_shap}** — SHAP computed on 1,000-patient background sample. "
                f"Expected value (baseline prediction): **{float(ev):.4f}** "
                f"({float(ev)*100:.1f}% baseline mortality).")

    shap_view = st.radio(
        "Select View",
        ["🐝 Beeswarm (Global)", "📊 Feature Importance Bar",
         "🔗 Dependence Plots", "🌊 Waterfall (Individual)", "🌐 All Models Comparison"],
        horizontal=True, key="shap_view",
    )
    st.markdown("---")

    sv    = shap_data[sel_model_shap]["shap_values"]
    X_shp = shap_data[sel_model_shap]["data"]

    # ── Beeswarm
    if shap_view == "🐝 Beeswarm (Global)":
        st.markdown("""
### Beeswarm Plot — Global Feature Effects
Each dot = one patient. **Color** = feature value (red=high, blue=low).
**X-axis** = SHAP value (right → increases death risk, left → decreases).
""")
        show_img(os.path.join(SHAP_DIR, f"shap_beeswarm_{sel_model_shap.replace(' ','_')}.png"))
        st.markdown("""
**Reading guide:**
- **Wide horizontal spread** → high variance in this feature's impact (complex, non-linear effect)
- **Monotone colour gradient** (left→right as colour changes) → clear directional effect
- **Mixed colours** at similar SHAP values → context-dependent, interacts with other features
""")

    # ── Bar
    elif shap_view == "📊 Feature Importance Bar":
        st.markdown("### Feature Importance Bar — Mean |SHAP|")
        st.markdown("Average absolute SHAP value across all patients — shows *magnitude* of impact, regardless of direction.")
        show_img(os.path.join(SHAP_DIR, f"shap_bar_{sel_model_shap.replace(' ','_')}.png"))

        mean_abs = np.abs(sv).mean(axis=0)
        imp_ser  = pd.Series(mean_abs, index=ALL_FEATURES).sort_values(ascending=False)

        c_tbl, c_chart = st.columns(2)
        with c_tbl:
            st.markdown("#### Ranked Table")
            tbl = imp_ser.reset_index()
            tbl.columns = ["Feature","Mean |SHAP|"]
            tbl["Rank"] = range(1, len(tbl)+1)
            tbl["Mean |SHAP|"] = tbl["Mean |SHAP|"].round(5)
            st.dataframe(tbl.set_index("Rank"), use_container_width=True)
        with c_chart:
            fig_bar_px = px.bar(
                tbl, x="Mean |SHAP|", y="Feature", orientation="h",
                color="Mean |SHAP|", color_continuous_scale="Reds",
                title=f"SHAP Importance — {sel_model_shap}",
            )
            fig_bar_px.update_layout(height=480, plot_bgcolor="#f8f9fa",
                                      yaxis=dict(autorange="reversed"))
            st.plotly_chart(fig_bar_px, use_container_width=True)

    # ── Dependence
    elif shap_view == "🔗 Dependence Plots":
        st.markdown("### Dependence Plots — Feature Value vs. SHAP Value")
        st.markdown("Shows how a feature's SHAP value changes with its actual value. "
                    "An automatically chosen interaction feature colours the dots.")
        show_img(os.path.join(SHAP_DIR, f"shap_dependence_{sel_model_shap.replace(' ','_')}.png"))

        st.markdown("#### 🎛️ Custom Dependence Plot")
        feat_pick = st.selectbox("Feature to explore", ALL_FEATURES, key="dep_feat2")
        fi = ALL_FEATURES.index(feat_pick)
        shap_feat = sv[:, fi]
        feat_vals = X_shp[feat_pick].values

        fig_dep = px.scatter(
            x=feat_vals, y=shap_feat, opacity=0.45,
            labels={"x": feat_pick, "y": f"SHAP ({feat_pick})"},
            title=f"SHAP Dependence — {feat_pick} | {sel_model_shap}",
            color=shap_feat, color_continuous_scale="RdBu_r",
            trendline="lowess",
        )
        fig_dep.add_hline(y=0, line_dash="dash", line_color="gray",
                          annotation_text="No effect")
        fig_dep.update_layout(height=420, plot_bgcolor="#f8f9fa")
        st.plotly_chart(fig_dep, use_container_width=True)

        st.markdown(f"""
**Interpretation of {feat_pick}:**
- Points **above 0** → this feature value *increases* predicted mortality
- Points **below 0** → this feature value *decreases* predicted mortality
- **Flat pattern** → feature has low predictive value for this model
""")

    # ── Waterfall
    elif shap_view == "🌊 Waterfall (Individual)":
        st.markdown("### Waterfall Plot — Individual Prediction Breakdown")
        st.markdown("Shows how each feature 'pushed' the model output above or below the baseline "
                    "(expected value) for a single patient.")

        n_patients = len(X_shp)
        row_idx    = st.slider("Select patient index", 0, n_patients-1, 0, key="wf_idx")

        row_sv   = sv[row_idx]
        row_data = X_shp.iloc[row_idx]
        ev_wf    = float(ev)
        pred_wf  = ev_wf + float(row_sv.sum())

        df_wf = pd.DataFrame({
            "Feature": ALL_FEATURES,
            "SHAP":    row_sv,
            "Value":   row_data.values,
        }).assign(Label=lambda d: d.apply(lambda r: f"{r['Feature']} = {r['Value']:.2f}", axis=1))
        df_wf = df_wf.sort_values("SHAP", key=np.abs, ascending=False).head(16)

        fig_wf = go.Figure(go.Bar(
            y=df_wf["Label"], x=df_wf["SHAP"], orientation="h",
            marker_color=["#F44336" if v > 0 else "#2196F3" for v in df_wf["SHAP"]],
            text=[f"{v:+.4f}" for v in df_wf["SHAP"]], textposition="outside",
        ))
        fig_wf.add_vline(x=0, line_color="black", line_width=1.5)
        fig_wf.update_layout(
            title=(f"Waterfall — Patient #{row_idx} | "
                   f"Baseline: {ev_wf:.4f} | Prediction: {pred_wf:.4f}"),
            xaxis_title="SHAP Value  (→ increases mortality risk)", height=520,
            plot_bgcolor="#f8f9fa",
        )
        st.plotly_chart(fig_wf, use_container_width=True)

        c_data, c_interp = st.columns(2)
        with c_data:
            st.markdown("**Patient's Feature Values**")
            st.dataframe(
                row_data.reset_index().rename(columns={"index":"Feature",0:"Value"}),
                use_container_width=True,
            )
        with c_interp:
            risk    = "🔴 HIGH RISK" if pred_wf > 0.5 else "🟢 LOW RISK"
            bg_clr  = "#FFEBEE" if pred_wf > 0.5 else "#E8F5E9"
            brd_clr = "#F44336" if pred_wf > 0.5 else "#2E7D32"
            pos_drivers = df_wf[df_wf["SHAP"]>0]["Feature"].head(3).tolist()
            neg_drivers = df_wf[df_wf["SHAP"]<0]["Feature"].head(3).tolist()
            st.markdown(f"""
<div style="background:{bg_clr}; border-left:5px solid {brd_clr}; padding:14px; border-radius:8px">
<strong>Mortality Probability: {pred_wf*100:.1f}%</strong><br>
<strong>Risk Classification: {risk}</strong><br><br>
<strong>Baseline (avg patient):</strong> {ev_wf*100:.1f}%<br>
<strong>Net SHAP shift:</strong> {(pred_wf-ev_wf)*100:+.1f} pp<br><br>
<strong>Top risk-increasing features:</strong><br>
{'<br>'.join(['  → ' + f for f in pos_drivers]) or 'None'}<br><br>
<strong>Top risk-reducing features:</strong><br>
{'<br>'.join(['  → ' + f for f in neg_drivers]) or 'None'}
</div>
""", unsafe_allow_html=True)

    # ── All Models
    elif shap_view == "🌐 All Models Comparison":
        st.markdown("### SHAP Feature Importance — All Models")
        show_img(os.path.join(SHAP_DIR, "shap_importance_all_models.png"))

        st.markdown("### SHAP Heatmap (All Models × All Features)")
        show_img(os.path.join(SHAP_DIR, "shap_heatmap_all_models.png"))

        st.markdown("### 🎯 Interactive SHAP Importance Heatmap")
        imp_all_d = {}
        for nm, d in shap_data.items():
            imp_all_d[nm] = pd.Series(np.abs(d["shap_values"]).mean(axis=0), index=ALL_FEATURES)
        imp_all_df   = pd.DataFrame(imp_all_d)
        imp_all_norm = imp_all_df.div(imp_all_df.max(axis=0) + 1e-12, axis=1)

        fig_heat_px = px.imshow(
            imp_all_norm.T.round(3),
            labels=dict(x="Feature", y="Model", color="Norm. Importance"),
            color_continuous_scale="YlOrRd", text_auto=".2f",
            title="Normalized SHAP Feature Importance (All Models)",
        )
        fig_heat_px.update_layout(height=380, margin=dict(l=10,r=10,t=50,b=50))
        st.plotly_chart(fig_heat_px, use_container_width=True)

        st.markdown("### 🤝 Feature Ranking Agreement Across Models")
        rank_df  = imp_all_df.rank(ascending=False)
        rank_std = rank_df.std(axis=1).sort_values()

        fig_agree = px.bar(
            rank_std.reset_index().rename(columns={"index":"Feature", 0:"Rank Std Dev"}),
            x="Feature", y="Rank Std Dev",
            color="Rank Std Dev", color_continuous_scale="RdYlGn_r",
            title="Rank Standard Deviation Across Models (↓ = stronger consensus)",
        )
        fig_agree.update_layout(height=380, plot_bgcolor="#f8f9fa", xaxis=dict(tickangle=30))
        st.plotly_chart(fig_agree, use_container_width=True)

        st.markdown("""
<div class="insight-box">
💡 <strong>How to read the ranking agreement chart:</strong><br>
A low <em>Rank Std Dev</em> means all models agree on the importance rank of that feature.
Features with low variance are <em>robustly important</em> (or robustly irrelevant) across linear and
tree-based families — these are the features you should prioritize in clinical decision-support systems.
</div>
""", unsafe_allow_html=True)

        # Side-by-side beeswarm for all models
        st.markdown("### 🐝 Beeswarm Plots — All Models")
        beeswarm_files = {
            nm: os.path.join(SHAP_DIR, f"shap_beeswarm_{nm.replace(' ','_')}.png")
            for nm in shap_data
        }
        cols_bs = st.columns(2)
        for i, (nm, fp) in enumerate(beeswarm_files.items()):
            with cols_bs[i % 2]:
                st.markdown(f"**{nm}**")
                show_img(fp)
